# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: josiasdb
      MYSQL_ROOT_PASSWORD: pro-2357
    ports:
      - 3306:3306

  