CREATE TABLE PAIS(
id_pais NUMBER(38, 0) NOT NULL PRIMARY KEY,
nome VARCHAR2(50) NOT null
);

CREATE TABLE ESTADO(
id_estado NUMBER(38, 0) NOT NULL PRIMARY KEY,
id_pais NUMBER(38, 0) NOT NULL,
nome VARCHAR2(50) NOT NULL,
CONSTRAINT FK_ESTADO_PAIS FOREIGN KEY 
( id_pais ) REFERENCES PAIS( id_pais )
)

CREATE TABLE CIDADE(
id_cidade NUMBER(38, 0) NOT NULL,
id_estado NUMBER(38, 0) NOT NULL,
nome VARCHAR2(50) NOT NULL,
PRIMARY KEY(id_cidade, id_estado),
CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY 
( id_estado ) REFERENCES ESTADO( id_estado )
)

CREATE TABLE BAIRRO(
id_bairro NUMBER(38, 0) NOT NULL,
id_cidade NUMBER(38, 0) NOT NULL,
id_estado NUMBER(38, 0) NOT NULL,
nome VARCHAR2(50) NOT NULL,
PRIMARY KEY(id_bairro, id_cidade),
CONSTRAINT FK_BAIRRO_CIDADE FOREIGN KEY 
( id_cidade, id_estado ) REFERENCES CIDADE( id_cidade, id_estado )
)

CREATE TABLE ENDERECO(
id_endereco NUMBER(38, 0) NOT NULL PRIMARY KEY,
id_bairro NUMBER(38, 0) NOT NULL,
id_cidade NUMBER(38, 0) NOT  NULL,
logradouro VARCHAR2(255) NOT NULL,
numero NUMBER(38, 0) NOT NULL,
complemento VARCHAR(100),
cep CHAR(9),
CONSTRAINT FK_ENDERECO_BAIRRO FOREIGN KEY 
( id_bairro, id_cidade ) REFERENCES BAIRRO( id_bairro, id_cidade )
);