CREATE TABLE PROJECT (
    id NUMBER PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    max_errors NUMBER(1,0) NOT NULL,
    completed CHAR(1) CHECK (completed IN ('1', '0')) NOT NULL,
    score NUMBER(3,0) NOT NULL
);

CREATE SEQUENCE SEQ_PROJECT
START WITH 1
INCREMENT BY 1
NOCACHE;