SELECT *
FROM Pessoa p
RIGHT JOIN Contato c
ON p.ID_PESSOA = c.ID_PESSOA ;

SELECT *
FROM Pessoa p
RIGHT JOIN PESSOA_X_PESSOA_ENDERECO ppe
ON p.ID_PESSOA = ppe.ID_PESSOA 
RIGHT JOIN Endereco_Pessoa ep
ON ppe.ID_ENDERECO = ep.ID_ENDERECO;

SELECT *
FROM Pessoa p
RIGHT JOIN Contato c
ON p.ID_PESSOA = c.ID_PESSOA 
RIGHT JOIN PESSOA_X_PESSOA_ENDERECO ppe
ON p.ID_PESSOA = ppe.ID_PESSOA 
RIGHT JOIN Endereco_Pessoa ep 
ON ppe.ID_ENDERECO  = ep.ID_ENDERECO;

SELECT *
FROM Pessoa p
FULL JOIN Contato c
ON p.ID_PESSOA = c.ID_PESSOA ;

SELECT *
FROM Pessoa p
FULL JOIN PESSOA_X_PESSOA_ENDERECO ppe
ON p.ID_PESSOA = ppe.ID_PESSOA 
FULL JOIN Endereco_Pessoa ed
ON ppe.ID_ENDERECO = ed.ID_ENDERECO;

SELECT *
FROM Pessoa p
FULL JOIN Contato c
ON p.ID_PESSOA = c.ID_PESSOA 
FULL JOIN PESSOA_X_PESSOA_ENDERECO ppe
ON p.ID_PESSOA = ppe.ID_PESSOA 
FULL JOIN Endereco_Pessoa ep
ON ppe.ID_ENDERECO = ep.ID_ENDERECO ;

SELECT *
FROM Pessoa p
WHERE EXISTS (
    SELECT 1
    FROM PESSOA_X_PESSOA_ENDERECO ppe
    WHERE ppe.ID_PESSOA = p.ID_PESSOA
);

SELECT p.ID_PESSOA , p.NOME , ep.ID_ENDERECO 
AS endereco_id, ep.logradouro
FROM Pessoa p
JOIN PESSOA_X_PESSOA_ENDERECO ppe 
ON p.ID_PESSOA = ppe.ID_PESSOA 
JOIN Endereco_Pessoa ep 
ON ppe.ID_ENDERECO = ep.ID_ENDERECO ;